ecords:
  build: records
  ports:
    - "8080"
  links:
    - mymongo

tasks:
  build: tasks
  ports:
    - "8080"
  links:
    - mymongo

students:
  build: students
  ports:
    - "8080"
  links:
    - mymongo

mymongo:
  image: mongo